0812checkbox
NewDadaFE/react-impression pull request #537
Opened 2020-08-20 06:42 UTC by zhangjuan01

optimize checkbox css

2020-08-20 09:25 UTC, lusssn requested changes

2020-08-20 09:25 UTC, lusssn commented on packages/react-impression/src/styles/modules/_checkbox.scss
> +        left: ($checkbox-addon-size  -$checkbox-indeterminate-i-size) * $font-size-root / 2 - 1;
top、left 计算方式一样，新增一个变量 
$checkbox-addon-offset-x: xxx;
$checkbox-addon-offset-y: $checkbox-addon-offset-x;

top: $checkbox-addon-offset-y;
left: $checkbox-addon-offset-x;

2020-08-20 09:25 UTC, lusssn commented on packages/react-impression/src/styles/modules/_checkbox.scss
> +        height: round($checkbox-indeterminate-i-size * $font-size-root);
这里为什么要 * $font-size-root ?

2020-08-20 09:25 UTC, lusssn commented on packages/react-impression/src/styles/variables/_checkbox.scss
>  $checkbox-addon-indeterminate-color: $checkbox-addon-checked-color !default;
无用变量请清理一下。

2020-08-24 03:08 UTC, lusssn approved these changes

2020-08-24 07:03 UTC, konghuachao001 approved these changes

2020-08-24 07:08 UTC, merged