button 组件重构
NewDadaFE/react-impression pull request #545
Opened 2020-08-28 10:52 UTC by yujiantao4616

1. 主题样式 添加dashed 边框按钮，default 默认样式按钮，text 文字按钮，移除secendory 次级按钮。
2.按钮大小 添加超小号按钮
3.其他修改 文字按钮移除超链接href属性，移除close关闭样式按钮，按钮添加加载中状态。按钮样式修改

2020-08-28 11:07 UTC, lusssn requested changes

2020-08-28 11:07 UTC, lusssn commented on packages/react-impression/src/components/Button/Button.js
>            className
建议多个className判断是否需要添加：
classnames({
  'btn-block': block,
  close: close,
 ...
})

2020-08-31 10:19 UTC, lusssn approved these changes

2020-08-31 11:27 UTC, konghuachao001 approved these changes

2020-08-31 11:41 UTC, merged