重构switch组件
NewDadaFE/react-impression pull request #549
Opened 2020-09-09 02:24 UTC by yujiantao4616

1.改变组件默认的大小，新增加一个小号的开关组件。
2.开关组件为选中状态的颜色修改。
2.新增加载中的状态。

2020-09-09 02:40 UTC, lusssn requested changes
新增的样式类名称添加前缀 .dada-

2020-09-09 02:40 UTC, lusssn commented on packages/react-impression/src/styles/modules/_switch.scss
> +.switch-spinner {
.switch-spinner -> .dada-switch-spinner

2020-09-09 02:40 UTC, lusssn commented on packages/react-impression/src/styles/modules/_switch.scss
> +.switch-sm.switch-addon {
.switch-sm -> .dada-switch-sm

2020-09-09 02:40 UTC, lusssn commented on packages/react-impression/src/styles/modules/_switch.scss
> +      & + .switch-loading {
.switch-loading -> .dada-switch-loading

2020-09-10 03:39 UTC, lusssn approved these changes

2020-09-10 05:25 UTC, konghuachao001 approved these changes

2020-09-10 06:18 UTC, merged