fix pagination select
NewDadaFE/react-impression pull request #561
Opened 2020-09-27 09:01 UTC by zhangjuan01

1.修复pagination的totalPage不更新的问题
2.修复select样式问题
3.checkbox，textLink使用语义化颜色

2020-09-27 09:49 UTC, lusssn requested changes

2020-09-27 09:49 UTC, lusssn commented on packages/react-impression/src/components/Pagination/Pagination.js
> +    if (totalPages <= 3 + scopeLength) {
这个 3 提出一个全局静态变量，scope默认值和这里都引用这个变量。

2020-09-27 09:49 UTC, lusssn commented on packages/react-impression/src/components/Pagination/Pagination.js
> +      activePage !== totalPages - 2
为什么是 2 ？

2020-09-27 09:49 UTC, lusssn commented on packages/react-impression/src/components/Pagination/Pagination.js
>      } = this.props
删除对象中普通字段：delete others.pageSize

2020-09-27 09:49 UTC, lusssn commented on packages/react-impression/src/components/Pagination/Pagination.js
> +                >{`${item}条/页`}</SelectOption>
格式化一下

2020-09-27 14:30 UTC, lusssn approved these changes

2020-09-28 08:00 UTC, gwt9502 approved these changes

2020-09-28 08:05 UTC, merged