Confirm
NewDadaFE/react-impression pull request #575
Opened 2020-11-18 02:47 UTC by yujiantao4616

- 添加 title 属性，confirm 显示的区分文案和标题
- 样式修改 info 类型 和 warning、danger 作出区分

2020-11-18 03:44 UTC, gwt9502 approved these changes

2020-11-19 07:39 UTC, lusssn requested changes

2020-11-19 07:39 UTC, lusssn commented on packages/react-impression/src/components/Confirm/Confirm.js
> +      <div {...others} className='confirm-dialog'>
others 用 @emotion/is-prop-valid 做过滤后再透传

2020-11-24 08:05 UTC, lusssn approved these changes

2020-11-24 08:05 UTC, merged